---
name: github pages
on:
  push:
    branches:
      - master
    paths-ignore: ['paper/**', 'README.md', 'LICENSE.txt']
  pull_request:
    branches:
      - master
    paths-ignore: ['paper/**', 'README.md', 'LICENSE.txt']
permissions:
  contents: write
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            lfs: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - run: mvn clean install
      - run: mkdir gh-pages
      - run: cp -r target/eo-after/. gh-pages
      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: gh-pages
